### ISSUE TITLE
Please upgrade the packages used

### ISSUE THREAD

**Issue by shivam-modi** [kfiross/chat_pickers#4]
The packages used are pretty old ones. Please update the packages

**Comment by d7h** [comment]
👍

**Comment by kfiross** [comment]
@shivam-modi I'll update it soon

**Comment by ErnestDaDev** [comment]
@kfiross still no update for the mongodb realm package?

**Comment by priyeshstackapp** [comment]
@kfiross any update?

**Comment by kfiross** [comment]
At the moment you can use the git-based null-safety version, on `pubspec.yaml`:
```
chat_pickers:
    git:
      url: https://github.com/kfiross/chat_pickers.git
      ref: migrate_to_nullsafety
```
